#!/bin/bash

echo "🚀 Starting Comprehensive Employee Monitoring System Demo"
echo "========================================================="
echo ""

# Check if backend is running
echo "📡 Checking backend server..."
if curl -s http://localhost:3001/health > /dev/null; then
    echo "✅ Backend server is running on port 3001"
else
    echo "🔄 Starting backend server..."
    node simple_backend.js &
    BACKEND_PID=$!
    echo "✅ Backend server started (PID: $BACKEND_PID)"
    sleep 2
fi

echo ""
echo "🔍 Comprehensive Monitoring Features Available:"
echo "=============================================="
echo ""
echo "📊 REAL-TIME ACTIVITY TRACKING:"
echo "  ⌨️  Keystroke monitoring with context"
echo "  🖱️  Mouse events and coordinates"
echo "  🖥️  Application usage and switching"
echo "  🌐 Browser activity and URL tracking"
echo "  📁 File operations and access patterns"
echo "  📸 Automated screenshot capture"
echo "  ⏱️  Idle time detection"
echo "  📈 Productivity scoring and analytics"
echo ""
echo "🔒 PRIVACY & COMPLIANCE:"
echo "  ✅ GDPR-compliant consent management"
echo "  🔐 End-to-end data encryption"
echo "  👁️  Complete data transparency"
echo "  📤 Data export capabilities"
echo "  ⚙️  Granular privacy controls"
echo ""
echo "📱 USER INTERFACE:"
echo "  📋 Employee dashboard with real-time counters"
echo "  📊 Detailed activity tabs (8 categories)"
echo "  📈 Productivity analytics and insights"
echo "  🎯 Role-based access control"
echo "  📊 Manager and admin dashboards"
echo ""

echo "🎯 DEMO ACCOUNTS:"
echo "================"
echo "👤 Employee: employee@demo.com / Demo123!"
echo "👥 Manager:  manager@demo.com / Demo123!"
echo "🔧 Admin:    admin@demo.com / Demo123!"
echo ""

echo "🔧 TECHNICAL ARCHITECTURE:"
echo "=========================="
echo "📱 Flutter UI with Material Design 3"
echo "🍎 Native macOS integration (Swift + Accessibility APIs)"
echo "🔄 Real-time event processing and batching"
echo "💾 Secure local storage with AES encryption"
echo "🌐 RESTful API with JWT authentication"
echo "📊 AI-powered productivity classification"
echo ""

echo "📋 MONITORING CAPABILITIES:"
echo "==========================="
echo ""
echo "1. KEYSTROKE MONITORING:"
echo "   • Every key press with timing and context"
echo "   • Modifier keys (Shift, Ctrl, Alt, Cmd)"
echo "   • Typing speed and rhythm analysis"
echo "   • Application and window context"
echo ""
echo "2. MOUSE ACTIVITY:"
echo "   • Click events with coordinates"
echo "   • Mouse movements and patterns"
echo "   • Scroll wheel activity"
echo "   • Drag and drop operations"
echo ""
echo "3. APPLICATION TRACKING:"
echo "   • App launches, exits, and focus changes"
echo "   • Time spent in each application"
echo "   • Process information and resource usage"
echo "   • Application switching frequency"
echo ""
echo "4. BROWSER MONITORING:"
echo "   • URLs visited and page titles"
echo "   • Time spent on websites/domains"
echo "   • Tab management and navigation"
echo "   • Form interactions and downloads"
echo ""
echo "5. FILE SYSTEM MONITORING:"
echo "   • Files opened, saved, created, deleted"
echo "   • File paths, sizes, and types"
echo "   • Access permissions and timestamps"
echo "   • Application file associations"
echo ""
echo "6. SCREEN CAPTURE:"
echo "   • Automated screenshots every 30 seconds"
echo "   • Context-aware metadata capture"
echo "   • Multi-monitor support"
echo "   • Encrypted storage with thumbnails"
echo ""
echo "7. PRODUCTIVITY ANALYTICS:"
echo "   • Real-time productivity scoring (0-100%)"
echo "   • Application categorization (productive/neutral/distracting)"
echo "   • Time distribution analysis"
echo "   • Activity pattern recognition"
echo ""

echo "🚀 STARTING FLUTTER APPLICATION:"
echo "================================"
echo ""
echo "The Flutter app will launch with comprehensive monitoring capabilities."
echo "You can:"
echo "  1. Login with any demo account"
echo "  2. Navigate to 'Detailed Monitoring' in Quick Actions"
echo "  3. Start comprehensive monitoring"
echo "  4. View real-time activity data across 8 detailed tabs"
echo "  5. Export your complete activity data"
echo ""

# Try to run Flutter app
echo "🔄 Launching Flutter application..."
flutter run -d macos --dart-define=API_BASE_URL=http://localhost:3001/v1 --dart-define=MOCK_DATA=true

echo ""
echo "📚 DOCUMENTATION:"
echo "================"
echo "📖 Comprehensive Guide: COMPREHENSIVE_MONITORING_GUIDE.md"
echo "🏗️  Architecture: ENTERPRISE_ARCHITECTURE.md"
echo "🔧 Setup Guide: SETUP_GUIDE.md"
echo "📋 Project Summary: PROJECT_SUMMARY.md"
echo ""
echo "🎉 Demo completed! The comprehensive monitoring system is ready for use."